In this workplace I will try to combine two dataset
* Train
* Test
  
Then i will do some Data Preprocessing steps:

* Data Cleaning: Handle missing values, remove duplicates, and correct errors.
* Feature Engineering: Create new features or modify existing ones to improve the model's performance.
* Data Transformation: Normalize, standardize, or encode categorical variables.
* Splitting Data: Split the data into training, validation, and test sets.

Then i will split them into two parts like train and test dataset.

In [1]:
import pandas as pd
import numpy as np
train = pd.read_csv('datas/train.csv')
test = pd.read_csv('datas/test.csv')

In [2]:
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [4]:
df = pd.concat([test.assign(ind="test"), train.assign(ind="train")])
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,ind,SalePrice
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,6,2010,WD,Normal,test,NaN
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,Gar2,12500,6,2010,WD,Normal,test,NaN
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,NaN,MnPrv,NaN,0,3,2010,WD,Normal,test,NaN
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2010,WD,Normal,test,NaN
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,NaN,NaN,NaN,0,1,2010,WD,Normal,test,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2007,WD,Normal,train,175000.0
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,2,2010,WD,Normal,train,210000.0
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,train,266500.0
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2010,WD,Normal,train,142125.0
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,Normal,train,147500.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2919 entries, 0 to 1459
Data columns (total 82 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     1153 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  ind            2919 non-null   object
 81  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(26), object(44)
memory usage: 1.8+ MB

In [6]:
df['ind'].value_counts()

ind
train    1460
test     1459
Name: count, dtype: int64

In [7]:
df.drop('Alley', inplace=True, axis=1)

In [8]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,ind,SalePrice
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,...,NaN,MnPrv,NaN,0,6,2010,WD,Normal,test,NaN
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,...,NaN,NaN,Gar2,12500,6,2010,WD,Normal,test,NaN
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,...,NaN,MnPrv,NaN,0,3,2010,WD,Normal,test,NaN
3,1464,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,Inside,...,NaN,NaN,NaN,0,6,2010,WD,Normal,test,NaN
4,1465,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,Inside,...,NaN,NaN,NaN,0,1,2010,WD,Normal,test,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,NaN,NaN,NaN,0,8,2007,WD,Normal,train,175000.0
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,NaN,MnPrv,NaN,0,2,2010,WD,Normal,train,210000.0
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,train,266500.0
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,NaN,NaN,NaN,0,4,2010,WD,Normal,train,142125.0
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,NaN,NaN,NaN,0,6,2008,WD,Normal,train,147500.0

In [9]:
# I have converted all the object into category
for label in df.keys():
    if df[label].dtype == 'O':
        df[label] = df[label].astype('category')

In [10]:
# I added 1 to all the cat codes 
for label in df.keys():
    if df[label].dtype == 'category':
        df[label] = df[label].cat.codes + 1

In [11]:
# Created an dic for see which column has Null value and what's their type
def checking_null():
    info_dic = {}
    for label, column in df.items():
        if column.isna().sum() > 0:
            info_dic[label] = column.isna().sum()
            info_dic[label + '_dtype'] = df[label].dtype

    return info_dic

In [12]:
checking_null()

{'LotFrontage': 486,
 'LotFrontage_dtype': dtype('float64'),
 'MasVnrArea': 23,
 'MasVnrArea_dtype': dtype('float64'),
 'BsmtFinSF1': 1,
 'BsmtFinSF1_dtype': dtype('float64'),
 'BsmtFinSF2': 1,
 'BsmtFinSF2_dtype': dtype('float64'),
 'BsmtUnfSF': 1,
 'BsmtUnfSF_dtype': dtype('float64'),
 'TotalBsmtSF': 1,
 'TotalBsmtSF_dtype': dtype('float64'),
 'BsmtFullBath': 2,
 'BsmtFullBath_dtype': dtype('float64'),
 'BsmtHalfBath': 2,
 'BsmtHalfBath_dtype': dtype('float64'),
 'GarageYrBlt': 159,
 'GarageYrBlt_dtype': dtype('float64'),
 'GarageCars': 1,
 'GarageCars_dtype': dtype('float64'),
 'GarageArea': 1,
 'GarageArea_dtype': dtype('float64'),
 'SalePrice': 1459,
 'SalePrice_dtype': dtype('float64')}

In [13]:
# I have created another column for is null property
for label in df.keys(): 
    if df[label].isna().sum() > 0:
        df[label + '_ismissing'] = df[label].isnull()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2919 entries, 0 to 1459
Data columns (total 93 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      2919 non-null   int64
 1   MSSubClass              2919 non-null   int64
 2   MSZoning                2919 non-null   int8
 3   LotFrontage             2433 non-null   float64
 4   LotArea                 2919 non-null   int64
 5   Street                  2919 non-null   int8
 6   LotShape                2919 non-null   int8
 7   LandContour             2919 non-null   int8
 8   Utilities               2919 non-null   int8
 9   LotConfig               2919 non-null   int8
 10  LandSlope               2919 non-null   int8
 11  Neighborhood            2919 non-null   int8
 12  Condition1              2919 non-null   int8
 13  Condition2              2919 non-null   int8
 14  BldgType                2919 non-null   int8
 15  HouseStyle              2919 non-null   int8
 16  OverallQual             2919 non-null   int64
 17  OverallCond             2919 non-null   int64
 18  YearBuilt               2919 non-null   int64
 19  YearRemodAdd            2919 non-null   int64
 20  RoofStyle               2919 non-null   int8
 21  RoofMatl                2919 non-null   int8
 22  Exterior1st             2919 non-null   int8
 23  Exterior2nd             2919 non-null   int8
 24  MasVnrType              2919 non-null   int8
 25  MasVnrArea              2896 non-null   float64
 26  ExterQual               2919 non-null   int8
 27  ExterCond               2919 non-null   int8
 28  Foundation              2919 non-null   int8
 29  BsmtQual                2919 non-null   int8
 30  BsmtCond                2919 non-null   int8
 31  BsmtExposure            2919 non-null   int8
 32  BsmtFinType1            2919 non-null   int8
 33  BsmtFinSF1              2918 non-null   float64
 34  BsmtFinType2            2919 non-null   int8
 35  BsmtFinSF2              2918 non-null   float64
 36  BsmtUnfSF               2918 non-null   float64
 37  TotalBsmtSF             2918 non-null   float64
 38  Heating                 2919 non-null   int8
 39  HeatingQC               2919 non-null   int8
 40  CentralAir              2919 non-null   int8
 41  Electrical              2919 non-null   int8
 42  1stFlrSF                2919 non-null   int64
 43  2ndFlrSF                2919 non-null   int64
 44  LowQualFinSF            2919 non-null   int64
 45  GrLivArea               2919 non-null   int64
 46  BsmtFullBath            2917 non-null   float64
 47  BsmtHalfBath            2917 non-null   float64
 48  FullBath                2919 non-null   int64
 49  HalfBath                2919 non-null   int64
 50  BedroomAbvGr            2919 non-null   int64
 51  KitchenAbvGr            2919 non-null   int64
 52  KitchenQual             2919 non-null   int8
 53  TotRmsAbvGrd            2919 non-null   int64
 54  Functional              2919 non-null   int8
 55  Fireplaces              2919 non-null   int64
 56  FireplaceQu             2919 non-null   int8
 57  GarageType              2919 non-null   int8
 58  GarageYrBlt             2760 non-null   float64
 59  GarageFinish            2919 non-null   int8
 60  GarageCars              2918 non-null   float64
 61  GarageArea              2918 non-null   float64
 62  GarageQual              2919 non-null   int8
 63  GarageCond              2919 non-null   int8
 64  PavedDrive              2919 non-null   int8
 65  WoodDeckSF              2919 non-null   int64
 66  OpenPorchSF             2919 non-null   int64
 67  EnclosedPorch           2919 non-null   int64
 68  3SsnPorch               2919 non-null   int64
 69  ScreenPorch             2919 non-null   int64
 70  PoolArea                2919 non-null   int64
 71  PoolQC                  2919 non-null   int8
 72  Fence                   2919 non-null   int8
 73  MiscFeature             2919 non-null   int8
 74  MiscVal                 2919 non-null   int64
 75  MoSold                  2919 non-null   int64
 76  YrSold                  2919 non-null   int64
 77  SaleType                2919 non-null   int8
 78  SaleCondition           2919 non-null   int8
 79  ind                     2919 non-null   int8
 80  SalePrice               1460 non-null   float64
 81  LotFrontage_ismissing   2919 non-null   bool
 82  MasVnrArea_ismissing    2919 non-null   bool
 83  BsmtFinSF1_ismissing    2919 non-null   bool
 84  BsmtFinSF2_ismissing    2919 non-null   bool
 85  BsmtUnfSF_ismissing     2919 non-null   bool
 86  TotalBsmtSF_ismissing   2919 non-null   bool
 87  BsmtFullBath_ismissing  2919 non-null   bool
 88  BsmtHalfBath_ismissing  2919 non-null   bool
 89  GarageYrBlt_ismissing   2919 non-null   bool
 90  GarageCars_ismissing    2919 non-null   bool
 91  GarageArea_ismissing    2919 non-null   bool
 92  SalePrice_ismissing     2919 non-null   bool
dtypes: bool(12), float64(12), int64(26), int8(43)
memory usage: 1.0 MB

In [15]:
df['LotFrontage_ismissing'].value_counts()

LotFrontage_ismissing
False    2433
True      486
Name: count, dtype: int64

In [16]:
# I filled all the numerical values
for label in df.keys(): 
    if df[label].isna().sum() > 0:
        mean = df[label].mean()
        df[label] = df[label].fillna(mean)

In [17]:
checking_null()

{}

In [18]:
# Convert bool into numerical type
for label in df.keys():
    if df[label].dtype == bool:
        df[label] = df[label].astype(int)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2919 entries, 0 to 1459
Data columns (total 93 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      2919 non-null   int64
 1   MSSubClass              2919 non-null   int64
 2   MSZoning                2919 non-null   int8
 3   LotFrontage             2919 non-null   float64
 4   LotArea                 2919 non-null   int64
 5   Street                  2919 non-null   int8
 6   LotShape                2919 non-null   int8
 7   LandContour             2919 non-null   int8
 8   Utilities               2919 non-null   int8
 9   LotConfig               2919 non-null   int8
 10  LandSlope               2919 non-null   int8
 11  Neighborhood            2919 non-null   int8
 12  Condition1              2919 non-null   int8
 13  Condition2              2919 non-null   int8
 14  BldgType                2919 non-null   int8
 15  HouseStyle              2919 non-null   int8
 16  OverallQual             2919 non-null   int64
 17  OverallCond             2919 non-null   int64
 18  YearBuilt               2919 non-null   int64
 19  YearRemodAdd            2919 non-null   int64
 20  RoofStyle               2919 non-null   int8
 21  RoofMatl                2919 non-null   int8
 22  Exterior1st             2919 non-null   int8
 23  Exterior2nd             2919 non-null   int8
 24  MasVnrType              2919 non-null   int8
 25  MasVnrArea              2919 non-null   float64
 26  ExterQual               2919 non-null   int8
 27  ExterCond               2919 non-null   int8
 28  Foundation              2919 non-null   int8
 29  BsmtQual                2919 non-null   int8
 30  BsmtCond                2919 non-null   int8
 31  BsmtExposure            2919 non-null   int8
 32  BsmtFinType1            2919 non-null   int8
 33  BsmtFinSF1              2919 non-null   float64
 34  BsmtFinType2            2919 non-null   int8
 35  BsmtFinSF2              2919 non-null   float64
 36  BsmtUnfSF               2919 non-null   float64
 37  TotalBsmtSF             2919 non-null   float64
 38  Heating                 2919 non-null   int8
 39  HeatingQC               2919 non-null   int8
 40  CentralAir              2919 non-null   int8
 41  Electrical              2919 non-null   int8
 42  1stFlrSF                2919 non-null   int64
 43  2ndFlrSF                2919 non-null   int64
 44  LowQualFinSF            2919 non-null   int64
 45  GrLivArea               2919 non-null   int64
 46  BsmtFullBath            2919 non-null   float64
 47  BsmtHalfBath            2919 non-null   float64
 48  FullBath                2919 non-null   int64
 49  HalfBath                2919 non-null   int64
 50  BedroomAbvGr            2919 non-null   int64
 51  KitchenAbvGr            2919 non-null   int64
 52  KitchenQual             2919 non-null   int8
 53  TotRmsAbvGrd            2919 non-null   int64
 54  Functional              2919 non-null   int8
 55  Fireplaces              2919 non-null   int64
 56  FireplaceQu             2919 non-null   int8
 57  GarageType              2919 non-null   int8
 58  GarageYrBlt             2919 non-null   float64
 59  GarageFinish            2919 non-null   int8
 60  GarageCars              2919 non-null   float64
 61  GarageArea              2919 non-null   float64
 62  GarageQual              2919 non-null   int8
 63  GarageCond              2919 non-null   int8
 64  PavedDrive              2919 non-null   int8
 65  WoodDeckSF              2919 non-null   int64
 66  OpenPorchSF             2919 non-null   int64
 67  EnclosedPorch           2919 non-null   int64
 68  3SsnPorch               2919 non-null   int64
 69  ScreenPorch             2919 non-null   int64
 70  PoolArea                2919 non-null   int64
 71  PoolQC                  2919 non-null   int8
 72  Fence                   2919 non-null   int8
 73  MiscFeature             2919 non-null   int8
 74  MiscVal                 2919 non-null   int64
 75  MoSold                  2919 non-null   int64
 76  YrSold                  2919 non-null   int64
 77  SaleType                2919 non-null   int8
 78  SaleCondition           2919 non-null   int8
 79  ind                     2919 non-null   int8
 80  SalePrice               2919 non-null   float64
 81  LotFrontage_ismissing   2919 non-null   int32
 82  MasVnrArea_ismissing    2919 non-null   int32
 83  BsmtFinSF1_ismissing    2919 non-null   int32
 84  BsmtFinSF2_ismissing    2919 non-null   int32
 85  BsmtUnfSF_ismissing     2919 non-null   int32
 86  TotalBsmtSF_ismissing   2919 non-null   int32
 87  BsmtFullBath_ismissing  2919 non-null   int32
 88  BsmtHalfBath_ismissing  2919 non-null   int32
 89  GarageYrBlt_ismissing   2919 non-null   int32
 90  GarageCars_ismissing    2919 non-null   int32
 91  GarageArea_ismissing    2919 non-null   int32
 92  SalePrice_ismissing     2919 non-null   int32
dtypes: float64(12), int32(12), int64(26), int8(43)
memory usage: 1.1 MB

In [20]:
test, train = df[df["ind"].eq(1)], df[df["ind"].eq(2)]

In [21]:
df['ind'].value_counts()

ind
2    1460
1    1459
Name: count, dtype: int64

In [22]:
train['SalePrice']

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [23]:
test['SalePrice']

0       180921.19589
1       180921.19589
2       180921.19589
3       180921.19589
4       180921.19589
            ...
1454    180921.19589
1455    180921.19589
1456    180921.19589
1457    180921.19589
1458    180921.19589
Name: SalePrice, Length: 1459, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split

X = train.drop('SalePrice', axis=1)
y = train.SalePrice

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [25]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1168, 92), (292, 92), (1168,), (292,))

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge

# Creating models
models = {'LinearRegression': LinearRegression(),
          'RandomForestRegressor': RandomForestRegressor(),
          'Ridge': Ridge()}

In [28]:
from sklearn.metrics import root_mean_squared_error

def fit_and_score(models):
    model_scores = {}
    for label, model in models.items(): 
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        model_scores[label] = np.sqrt(root_mean_squared_error(y_test, y_pred))

    return model_scores

In [29]:
model1 = LinearRegression()
model1.fit(X_train, y_train)
asd = model1.predict(X_test)
root_mean_squared_error(y_test, asd)

37362.81117838508

In [30]:
scores = fit_and_score(models)

In [31]:
scores

{'LinearRegression': 193.29462273530808,
 'RandomForestRegressor': 170.62881371629763,
 'Ridge': 188.93016734234106}